version: "3.0.0.{build}"
image: Visual Studio 2019

before_build:
  - ps: "dotnet restore"
build:
  project: PuppeteerSharp.Contrib.sln
  verbosity: minimal
test_script:
  - ps: "dotnet test .\\tests\\PuppeteerSharp.Contrib.Tests\\PuppeteerSharp.Contrib.Tests.csproj"
